"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url # Import pour gérer l'URL de la base de données de production

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# --- CONFIGURATION DE PRODUCTION (RENDER) ---

# SECURITY WARNING: keep the secret key used in production secret!
# Lit la clé secrète depuis l'environnement (obligatoire en prod) ou utilise la valeur par défaut
SECRET_KEY = os.environ.get(
    'SECRET_KEY', 
    'django-insecure-mj^2l6g@5b2hlvd5lr5ib3dr_b(8!)29be6$66dm7qft!*1@2x' # Clé par défaut pour le dev local
)

# SECURITY WARNING: don't run with debug turned on in production!
# Lit le mode DEBUG depuis l'environnement. Doit être 'False' en production.
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# Autoriser toutes les hôtes pour le déploiement Render.
# Vous devriez restreindre à l'URL de Render une fois connue.
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'users',
]

# --- MIDDLEWARE DE PRODUCTION ---
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    
    # AJOUT ESSENTIEL POUR LA PROD: Whitenoise pour servir les fichiers statiques
    'whitenoise.middleware.WhiteNoiseMiddleware', 
    
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# --- CONFIGURATION DE BASE DE DONNÉES (MySQL/PostgreSQL pour Render) ---

# Lit l'URL de connexion (MySQL) depuis la variable d'environnement DATABASE_URL.
# Si la variable n'existe pas (en dev local), revient à SQLite.
if os.environ.get('DATABASE_URL'):
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=600,
            # Force le moteur MySQL pour les déploiements (si l'URL n'est pas claire)
            engine='django.db.backends.mysql' 
        )
    }
else:
    # Configuration SQLite par défaut pour le développement local
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# --- GESTION DES FICHIERS STATIQUES (WHITENOISE) ---

# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# Le dossier où Django/Whitenoise va collecter les fichiers statiques pour la production
STATIC_ROOT = BASE_DIR / 'staticfiles' 
# Stockage pour la compression et le cache des fichiers statiques
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'